name: deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t 983046/todo-app:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push 983046/todo-app:latest
    